spring:
    datasource:
        url: jdbc:mysql://localhost:3306/web?useUnicode=true&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
        schema: classpath:/data/schema.sql
        data: classpath:/data/data.sql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
logging:
    level:
        ROOT: INFO

