spring:
    datasource:
        url: jdbc:mysql://localhost:3306/web?useUnicode=true&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
        schema: classpath:/data/schema.sql
        data: classpath:/data/data.sql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
    data:
        mongodb:
            database: library
            #authentication-database: admin
            #username: root
            #password: root
            port: 27017
            host: localhost
    batch:
        initialize-schema: always
        job:
          enabled: true
logging:
    level:
        ROOT: INFO

